name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          ISSUE:  ${{ github.event.issue.title }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          if [[ $ISSUE == *"bug"* ]]; then
          echo "Issue is about a bug!"
          echo $GITHUB_CONTEXT
          else
          echo "Issue is not about a bug"
          echo $ISSUE
          echo ${{ env.ISSUE }}
          fi
